name       : libvoikko
version    : 4.2
release    : 10
source     :
    - https://www.puimula.org/voikko-sources/libvoikko/libvoikko-4.2.tar.gz : f13c59825f36152f388cd96f638e447744199775277f4e6bcd0b9483f0eebeca
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : Libvoikko provides spell checking, hyphenation, grammar checking and
    morphological analysis for Finnish language
description: |
    Libvoikko provides spell checking, hyphenation, grammar checking and morphological analysis for Finnish language.
setup      : |
    %configure \
        --disable-hfst \
        --disable-static \
        --with-dictionary-path=/usr/share/voikko
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 python/libvoikko.py $installdir/usr/lib/python%python3_version%/site-packages/libvoikko.py
