name       : libvoikko
version    : 4.1
release    : 1
source     :
    - http://www.puimula.org/voikko-sources/libvoikko/libvoikko-4.1.tar.gz : 8ecf4a352ff330594250dbc191e0843394f340061bdc6586f8ff2e281bce8e70
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.1
component  : programming.library
summary    : Libvoikko provides spell checking, hyphenation, grammar checking and morphological analysis for Finnish language.
description: |
    Libvoikko provides spell checking, hyphenation, grammar checking and morphological analysis for Finnish language.
setup      : |
    %configure \
        --disable-hfst \
        --disable-static \
        --with-dictionary-path=/usr/share/voikko
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 python/libvoikko.py $installdir/usr/lib/python3.5/site-packages/libvoikko.py
